import { CACHE_TAG_ARTICLES } from '@/collections/Articles/constants'
import type { Payload } from 'payload'

export const seedArticle = async (payload: Payload): Promise<void> => {
  const addArticle = [
    {
      title: 'The Future of WhatsApp in Banking: What’s Next for BFSI?',
      slug: 'the-future-of-whatsapp-in-banking-whats-next-for-bfsi',
      featuredImage: {
        id: 8,
        alt: null,
        caption: null,
        prefix: 'client/document',
        updatedAt: '2026-03-04T09:17:51.339Z',
        createdAt: '2026-03-04T09:17:51.208Z',
        url: '/api/media/file/whatsappBanking.3666b3cb.png',
        thumbnailURL: null,
        filename: 'whatsappBanking.3666b3cb.png',
        mimeType: 'image/png',
        filesize: 212953,
        width: 1200,
        height: 592,
        focalX: 50,
        focalY: 50,
      },
      shortDescription:
        'The Banking, Financial Services, and Insurance (BFSI) sector is undergoing rapid digital transformation, and WhatsApp banking is emerging as a key enabler of this change.',
      content: {
        root: {
          type: 'root',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              tag: 'h3',
              type: 'heading',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Why WhatsApp Is Revolutionizing BFSI',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              tag: 'h3',
              type: 'heading',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'High User Engagement',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              tag: 'ul',
              type: 'list',
              start: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'listitem',
                  value: 1,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'WhatsApp open rate exceeds 98%, vastly outperforming email and SMS.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: null,
                },
                {
                  type: 'listitem',
                  value: 2,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Most messages are read within minutes, ensuring real-time communication.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: null,
                },
              ],
              listType: 'bullet',
              direction: null,
            },
            {
              tag: 'h3',
              type: 'heading',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Conversational Banking That Feels Natural',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              tag: 'ul',
              type: 'list',
              start: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'listitem',
                  value: 1,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Customers can interact using WhatsApp chatbots, voice notes, or regional languages.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: null,
                },
                {
                  type: 'listitem',
                  value: 2,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'This improves engagement, particularly in Tier 2 and rural markets.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: null,
                },
              ],
              listType: 'bullet',
              direction: null,
            },
            {
              tag: 'h3',
              type: 'heading',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Cost-Effective and Scalable',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Compared to traditional call centers or physical branches, WhatsApp automation drastically lowers support costs.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
              textStyle: '',
              textFormat: 0,
            },
            {
              tag: 'h3',
              type: 'heading',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'WhatsApp Use Cases in BFSI',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Here are the most popular WhatsApp business use cases for banks:',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
              textStyle: '',
              textFormat: 0,
            },
            {
              tag: 'ol',
              type: 'list',
              start: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'listitem',
                  value: 1,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Customer Support via Chatbot',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 1,
                      version: 1,
                    },
                  ],
                  direction: null,
                  textFormat: 1,
                },
                {
                  type: 'listitem',
                  value: 2,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      tag: 'ul',
                      type: 'list',
                      start: 1,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          type: 'listitem',
                          value: 1,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Balance check, mini statement, account blocking',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                        {
                          type: 'listitem',
                          value: 2,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: '24/7 availability using AI-driven WhatsApp chatbots',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                      ],
                      listType: 'bullet',
                      direction: null,
                    },
                  ],
                  direction: null,
                },
                {
                  type: 'listitem',
                  value: 2,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Real-Time Transaction Alerts',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 1,
                      version: 1,
                    },
                  ],
                  direction: null,
                  textFormat: 1,
                },
                {
                  type: 'listitem',
                  value: 3,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      tag: 'ul',
                      type: 'list',
                      start: 1,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          type: 'listitem',
                          value: 1,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Fraud detection, OTPs, credit card spends, EMI reminders',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                        {
                          type: 'listitem',
                          value: 2,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Secure and instantly delivered',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                      ],
                      listType: 'bullet',
                      direction: null,
                    },
                  ],
                  direction: null,
                },
                {
                  type: 'listitem',
                  value: 3,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Loan and Credit Card Applications',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 1,
                      version: 1,
                    },
                  ],
                  direction: null,
                  textFormat: 1,
                },
                {
                  type: 'listitem',
                  value: 4,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      tag: 'ul',
                      type: 'list',
                      start: 1,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          type: 'listitem',
                          value: 1,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Eligibility checks, document collection via WhatsApp',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                        {
                          type: 'listitem',
                          value: 2,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Instant status updates and approvals',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                      ],
                      listType: 'bullet',
                      direction: null,
                    },
                  ],
                  direction: null,
                },
                {
                  type: 'listitem',
                  value: 4,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'KYC and Onboarding',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 1,
                      version: 1,
                    },
                  ],
                  direction: null,
                  textFormat: 1,
                },
                {
                  type: 'listitem',
                  value: 5,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      tag: 'ul',
                      type: 'list',
                      start: 1,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          type: 'listitem',
                          value: 1,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Use of OCR and Web View for document upload',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                        {
                          type: 'listitem',
                          value: 2,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Integration with Aadhaar/PAN systems for eKYC',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                      ],
                      listType: 'bullet',
                      direction: null,
                    },
                  ],
                  direction: null,
                },
              ],
              listType: 'number',
              direction: null,
            },
          ],
          direction: null,
        },
      },
      status: 'Published',
    },
    {
      title: 'The Future of WhatsApp in Banking: What’s Next for BFSI1?',
      slug: 'the-future-of-whatsapp-in-banking-whats-next-for-bfsi1',
     featuredImage: {
        id: 8,
        alt: null,
        caption: null,
        prefix: 'client/document',
        updatedAt: '2026-03-04T09:17:51.339Z',
        createdAt: '2026-03-04T09:17:51.208Z',
        url: '/api/media/file/whatsappBanking.3666b3cb.png',
        thumbnailURL: null,
        filename: 'whatsappBanking.3666b3cb.png',
        mimeType: 'image/png',
        filesize: 212953,
        width: 1200,
        height: 592,
        focalX: 50,
        focalY: 50,
      },
      shortDescription:
        'The Banking, Financial Services, and Insurance (BFSI) sector is undergoing rapid digital transformation, and WhatsApp banking is emerging as a key enabler of this change.',
      content: {
        root: {
          type: 'root',
          format: '',
          indent: 0,
          version: 1,
          children: [
            {
              tag: 'h3',
              type: 'heading',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Why WhatsApp Is Revolutionizing BFSI',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              tag: 'h3',
              type: 'heading',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'High User Engagement',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              tag: 'ul',
              type: 'list',
              start: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'listitem',
                  value: 1,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'WhatsApp open rate exceeds 98%, vastly outperforming email and SMS.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: null,
                },
                {
                  type: 'listitem',
                  value: 2,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Most messages are read within minutes, ensuring real-time communication.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: null,
                },
              ],
              listType: 'bullet',
              direction: null,
            },
            {
              tag: 'h3',
              type: 'heading',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Conversational Banking That Feels Natural',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              tag: 'ul',
              type: 'list',
              start: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'listitem',
                  value: 1,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Customers can interact using WhatsApp chatbots, voice notes, or regional languages.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: null,
                },
                {
                  type: 'listitem',
                  value: 2,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'This improves engagement, particularly in Tier 2 and rural markets.',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 0,
                      version: 1,
                    },
                  ],
                  direction: null,
                },
              ],
              listType: 'bullet',
              direction: null,
            },
            {
              tag: 'h3',
              type: 'heading',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Cost-Effective and Scalable',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Compared to traditional call centers or physical branches, WhatsApp automation drastically lowers support costs.',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
              textStyle: '',
              textFormat: 0,
            },
            {
              tag: 'h3',
              type: 'heading',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'WhatsApp Use Cases in BFSI',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
            },
            {
              type: 'paragraph',
              format: 'start',
              indent: 0,
              version: 1,
              children: [
                {
                  mode: 'normal',
                  text: 'Here are the most popular WhatsApp business use cases for banks:',
                  type: 'text',
                  style: '',
                  detail: 0,
                  format: 0,
                  version: 1,
                },
              ],
              direction: null,
              textStyle: '',
              textFormat: 0,
            },
            {
              tag: 'ol',
              type: 'list',
              start: 1,
              format: '',
              indent: 0,
              version: 1,
              children: [
                {
                  type: 'listitem',
                  value: 1,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Customer Support via Chatbot',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 1,
                      version: 1,
                    },
                  ],
                  direction: null,
                  textFormat: 1,
                },
                {
                  type: 'listitem',
                  value: 2,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      tag: 'ul',
                      type: 'list',
                      start: 1,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          type: 'listitem',
                          value: 1,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Balance check, mini statement, account blocking',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                        {
                          type: 'listitem',
                          value: 2,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: '24/7 availability using AI-driven WhatsApp chatbots',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                      ],
                      listType: 'bullet',
                      direction: null,
                    },
                  ],
                  direction: null,
                },
                {
                  type: 'listitem',
                  value: 2,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Real-Time Transaction Alerts',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 1,
                      version: 1,
                    },
                  ],
                  direction: null,
                  textFormat: 1,
                },
                {
                  type: 'listitem',
                  value: 3,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      tag: 'ul',
                      type: 'list',
                      start: 1,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          type: 'listitem',
                          value: 1,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Fraud detection, OTPs, credit card spends, EMI reminders',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                        {
                          type: 'listitem',
                          value: 2,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Secure and instantly delivered',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                      ],
                      listType: 'bullet',
                      direction: null,
                    },
                  ],
                  direction: null,
                },
                {
                  type: 'listitem',
                  value: 3,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'Loan and Credit Card Applications',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 1,
                      version: 1,
                    },
                  ],
                  direction: null,
                  textFormat: 1,
                },
                {
                  type: 'listitem',
                  value: 4,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      tag: 'ul',
                      type: 'list',
                      start: 1,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          type: 'listitem',
                          value: 1,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Eligibility checks, document collection via WhatsApp',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                        {
                          type: 'listitem',
                          value: 2,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Instant status updates and approvals',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                      ],
                      listType: 'bullet',
                      direction: null,
                    },
                  ],
                  direction: null,
                },
                {
                  type: 'listitem',
                  value: 4,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      mode: 'normal',
                      text: 'KYC and Onboarding',
                      type: 'text',
                      style: '',
                      detail: 0,
                      format: 1,
                      version: 1,
                    },
                  ],
                  direction: null,
                  textFormat: 1,
                },
                {
                  type: 'listitem',
                  value: 5,
                  format: 'start',
                  indent: 0,
                  version: 1,
                  children: [
                    {
                      tag: 'ul',
                      type: 'list',
                      start: 1,
                      format: '',
                      indent: 0,
                      version: 1,
                      children: [
                        {
                          type: 'listitem',
                          value: 1,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Use of OCR and Web View for document upload',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                        {
                          type: 'listitem',
                          value: 2,
                          format: '',
                          indent: 1,
                          version: 1,
                          children: [
                            {
                              mode: 'normal',
                              text: 'Integration with Aadhaar/PAN systems for eKYC',
                              type: 'text',
                              style: '',
                              detail: 0,
                              format: 0,
                              version: 1,
                            },
                          ],
                          direction: null,
                        },
                      ],
                      listType: 'bullet',
                      direction: null,
                    },
                  ],
                  direction: null,
                },
              ],
              listType: 'number',
              direction: null,
            },
          ],
          direction: null,
        },
      },
      status: 'Published',
    },
  ]

  for (const article of addArticle) {
    await payload.create({
      collection: CACHE_TAG_ARTICLES,
      data: article as any,
    })
  }
}
