import { CACHE_TAG_EMAIL_TEMP } from '@/collections/emailTemplate/constants'
import type { Payload } from 'payload'

export const seedEmailTemplate = async (payload: Payload) => {
  const template = [
    { template_name: 'sign_up', subject: 'Registration Successful – TenderBharo',body:'\u003Cp\u003EHi \u003Cspan style=\"font-weight: 600;\"\u003E{{name}}\u003C/span\u003E,\u003C/p\u003E\n\t\t\t\t\u003Cp\u003EWelcome to Tender Bharo Solutions\u003C/p\u003E\n\t\t\t\t\u003Cp style=\"margin-top: 0px;margin-bottom:15px;\"\u003EYour account has been successfully created. You can now explore live tenders, track opportunities, and stay updated with the latest procurement notices—all in one place.\u003C/p\u003E\n\t\t\t\t\n\t\t\t\t\u003Cp style=\"margin-bottom: 0px;margin-bottom:5px;\"\u003EGet started with\u003C/p\u003E\n\t\t\t\t\u003Cul\u003E\n\t\t\t\t\t\u003Cli\u003EAccess to live &amp; archived tenders\u003C/li\u003E\n\t\t\t\t\t\u003Cli\u003EEmail alerts for tenders matching your criteria\u003C/li\u003E\n\t\t\t\t\u003C/ul\u003E\n\t\t\t\t\u003Cp style=\"margin-top: 0px;margin-bottom:10px;\"\u003ETo unlock full access and premium features, you can review our available plans below:\u003C/p\u003E\n\t\t\t\t\u003Ca href=\"{{url}}/pricing\"  style=\"background-color: #03A9F5;color: #E1FCEF;text-decoration: none;padding: 8px 20px;border-radius: 10px;color: #E1FCEF;margin: 3px 0px;display: inline-block;\"\u003EView Pricing Plans\u003C/a\u003E\n\t\t\t\t\u003Cp style=\"margin-top: 10px;margin-bottom:15px;\"\u003EIf you need any assistance or have questions, our support team will be happy to help.\u003C/p\u003E\n\t\t\t\t\u003Cp\u003EThank you, \u003Cbr\u003E Tender Bharo Team,\u003Cbr\u003E\u003Ca href=\"mailto:support@tenderbharo.com\" style=\"color: #0D6EFD;\"\u003Esupport@tenderbharo.com\u003C/a\u003E\u003C/p\u003E' },
    { template_name: 'email_otp',subject:'Your Verification Code',body:'\u003Cp\u003EHi \u003Cspan style=\"font-weight: 600;\"\u003E{{name}}\u003C/span\u003E,\u003C/p\u003E\n\t\t\t\t\u003Cp style=\"margin-bottom: 0px;margin-bottom:15px\"\u003EYour One-Time Password (OTP) for verification is\u003C/p\u003E\n\t\t\t\t\u003Cdiv style=\"background-color: #DDF4FF;padding: 4px 3px;color: #03A9F5;font-size: 22px;text-align: center;letter-spacing: 3px;font-weight: 500;margin: 7px 0px\"\u003E{{otp}}\u003C/div\u003E\n\t\t\t\t\n\t\t\t\t\u003Cp style=\"margin-top: 0px;margin-bottom:15px\"\u003EThis OTP is valid for \u003Cspan style=\"font-weight: 600;\"\u003E10 minutes\u003C/span\u003E. Please do not share it with anyone for your account’s security.\u003C/p\u003E\n\t\t\t\t\u003Cp style=\"margin-bottom:15px\"\u003EIf you did not request this code, please ignore this message.\u003C/p\u003E\n\t\t\t\t\n\t\t\t\t\u003Cp\u003EThank you, \u003Cbr\u003E Tender Bharo Team,\u003Cbr\u003E\u003Ca href=\"mailto:support@tenderbharo.com\" style=\"color: #0D6EFD;\"\u003Esupport@tenderbharo.com\u003C/a\u003E\u003C/p\u003E'},
    { template_name: 'get_in_touch', subject: 'Thanks for contacting TenderBharo', body: '<p>Hi <span style=\"font-weight: 600;\">{{name}}</span>,</p>\n\t\t\t\t<p>Thank you for reaching out for <a href={{page_url}}> {{page}} </a> .</p>\n\t\t\t\t<p style=\"margin-top: 0px;margin-bottom:15px;\">We have received your message, and our team will review it carefully. We will get back to you shortly with further information..</p>\n\t\t\t\t<p>Regards, <br> Tender Bharo Team,<br><a href=\"mailto:support@tenderbharo.com\" style=\"color: #0D6EFD;\">support@tenderbharo.com</a></p>' },
    { template_name: 'reset_password', subject:'Reset your password',body:'\u003Cp\u003EHi \u003Cspan style=\"font-weight: 600;\"\u003E{{name}}\u003C/span\u003E,\u003C/p\u003E\n\t\t\t\t\u003Cp style=\"margin-bottom: 0px;\"\u003EWe received a request to reset your password for your account.\u003C/p\u003E\n\t\t\t\t\u003Cp style=\"margin-top: 0px;\"\u003EIf you made this request, please click the button below to create a new password:\u003C/p\u003E\n\t\t\t\t\u003Ca href={{url}} style=\"background-color: #14804A;color: #fff;text-decoration: none;padding: 8px 20px;border-radius: 10px;color: #E1FCEF;margin: 3px 0px;display: inline-block;\"\u003EReset Password\u003C/a\u003E\n\t\t\t\t\u003Cp\u003EThis link will expire in 30 minutes for security reasons.\u003C/p\u003E\n\t\t\t\t\u003Cp style=\"font-size: 13px;margin-bottom: 0px;\"\u003EIf you didn’t request a password reset, you can safely ignore this email — your account will remain secure.\u003C/p\u003E\n\t\t\t\t\n\t\t\t\t\u003Cp\u003EHappy to Help \u003Cbr\u003E Tender Bharo Team,\u003Cbr\u003E\u003Ca href=\"mailto:info@tenderbharo.com\" style=\"color: #0D6EFD;\"\u003Einfo@tenderbharo.com\u003C/a\u003E\u003C/p\u003E'},
    { template_name: 'update_password',subject:'Password Updated Successfully',body:'\u003Cp style=\"margin-bottom:15px\"\u003EHi \u003Cspan style=\"font-weight: 600;\"\u003E{{name}}\u003C/span\u003E,\u003C/p\u003E\n\t\t\t\t\u003Cp style=\"margin-top: 0px;margin-bottom:15px\"\u003EThis is to confirm that your account password for [Your Tender Platform Name] has been updated successfully.\u003C/p\u003E\n\t\t\t\t\u003Cp style=\"margin-top: 0px;margin-bottom:15px\"\u003EIf you made this change, no further action is required.\u003C/p\u003E\n\t\t\t\t\u003Cp style=\"margin-top: 0px;margin-bottom:0\"\u003EIf you did not update your password, please reset it immediately and contact our support team to keep your account secure.\u003C/p\u003E\n\t\t\t\t\u003Ca href={{url}} style=\"background-color: #14804A;color: #fff;text-decoration: none;padding: 8px 20px;border-radius: 10px;color: #E1FCEF;margin: 15px 0px;display: inline-block;\"\u003ELogin to your account\u003C/a\u003E\n\t\t\t\t\u003Cp style=\"margin-top: 0px;margin-bottom:15px\"\u003EIf you need any help, feel free to reach out to us.\u003C/p\u003E\n\t\t\t\t\n\t\t\t\t\u003Cp\u003EHappy to Help \u003Cbr\u003E Tender Bharo Team,\u003Cbr\u003E\u003Ca href=\"mailto:info@tenderbharo.com\" style=\"color: #0D6EFD;\"\u003Einfo@tenderbharo.com\u003C/a\u003E\u003C/p\u003E'},
    { template_name: 'invitation_to_join', subject:'Invitation to join {{businessName}} as Distributor',body:'<div style=\"font-family: sans-serif; padding: 20px; color: #333; line-height: 1.6;\">\n <h2 style=\"color: #007bff;\">Welcome to Tendersbharo!</h2>\n <p>Hello {{name}}</p>\n <p><strong>{{businessName}}</strong> has invited you to join their team as a distributor on Tendersbharo.</p>\n <p>To get started, please click the button below to set up your password and accept the invitation:</p>\n <div style=\"margin: 30px 0;\">\n <a href=\"{{url}}\" style=\"display: inline-block; padding: 12px 24px; background-color: #007bff; color: white; text-decoration: none; border-radius: 5px; font-weight: bold;\">Set Password & Accept Invitation</a>\n </div>\n <p>If you have any questions, please contact {{businessName}}.</p>\n <hr style=\"border: none; border-top: 1px solid #eee; margin: 20px 0;\" />\n <p style=\"font-size: 0.8em; color: #777;\">Thanks,<br/>The Tendersbharo Team</p>\n </div>'},
    { template_name: 'new_business_invitation', subject:'New Business Invitation from {{businessName}}',body:'<div style=\"font-family: sans-serif; padding: 20px; color: #333; line-height: 1.6;\">\n <h2 style=\"color: #007bff;\">Hello again!</h2>\n <p>Hello {{fullname}},</p>\n <p><strong>{{businessName}}</strong> has added you as a distributor on Tendersbharo.</p>\n <p>You have to accept this invitation to link your profile with {{businessName}}:</p>\n <div style=\"margin: 30px 0;\">\n <a href=\"{{url}}\" style=\"display: inline-block; padding: 12px 24px; background-color: #007bff; color: white; text-decoration: none; border-radius: 5px; font-weight: bold;\">Accept Invitation</a>\n </div>\n <p>If you have any questions, please contact {{businessName}}.</p>\n <hr style=\"border: none; border-top: 1px solid #eee; margin: 20px 0;\" />\n <p style=\"font-size: 0.8em; color: #777;\">Thanks,<br/>The Tendersbharo Team</p>\n </div>'},
    { template_name: 'new_tender_assign',subject:'New Tender Assigned: {{tenderTitle}}',body:'<div style=\"font-family: sans-serif; padding: 20px; color: #333;\">\n <h2 style=\"color: #0056b3;\">New Tender Assignment</h2>\n <p>Hello <strong>{{name}}</strong>,</p>\n <p>A new tender has been assigned to you for review and action.</p>\n <div style=\"background: #f4f4f4; padding: 15px; border-radius: 5px; margin: 20px 0;\">\n <p style=\"margin: 0;\"><strong>Tender Name:</strong> {{tenderTitle}}</p>\n <p style=\"margin: 5px 0 0 0;\"><strong>Tender ID:</strong> {{tenderId}}</p>\n </div>\n <p>Please log in to your dashboard to view the details and update the status.</p>\n <a href=\"{{url}}/login\" \n style=\"display: inline-block; padding: 10px 20px; background: #0056b3; color: white; text-decoration: none; border-radius: 5px;\">\n Log In to Account\n </a>\n </div>'},
    { template_name : 'user_enquiry_info',subject:'New Lead Submission for this {{page}} page.',body:'<table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#ffffff\" style=\"border-collapse:collapse;\">\n <tr>\n <td style=\"padding:20px;font-family:Arial, sans-serif;font-size:14px;color:#454545;\">\n Hi <strong>Team</strong>,\n </td>\n </tr>\n <tr>\n <td bgcolor=\"#2c3e50\" align=\"center\" \n style=\"color:#ffffff;padding:15px;font-family:Arial;font-size:18px;font-weight:bold;\">\n User Information Details\n </td>\n </tr>\n <tr>\n <td style=\"padding:20px;\">\n <table width=\"100%\" cellpadding=\"8\" cellspacing=\"0\" style=\"border-collapse:collapse;font-family:Arial;font-size:14px;\">\n\n <tr>\n <td style=\"border:1px solid #dddddd;font-weight:bold;width:40%;\">Full Name</td>\n <td style=\"border:1px solid #dddddd;\">{{name}</td>\n </tr>\n\n <tr>\n <td style=\"border:1px solid #dddddd;font-weight:bold;\">Email Address</td>\n <td style=\"border:1px solid #dddddd;\">{{email}}</td>\n </tr>\n\n <tr>\n <td style=\"border:1px solid #dddddd;font-weight:bold;\">Phone Number</td>\n <td style=\"border:1px solid #dddddd;\">{{mobile}}</td>\n </tr>\n\n <tr>\n <td style=\"border:1px solid #dddddd;font-weight:bold;\">Company Name</td>\n <td style=\"border:1px solid #dddddd;\">{{company_name}}</td>\n </tr>\n\n </table>\n </td>\n </tr>\n <tr>\n <td bgcolor=\"#f8f8f8\" align=\"center\"\n style=\"padding:15px;font-family:Arial;font-size:12px;color:#777777;\">\n This is an automated email. Please do not reply.\n </td>\n </tr>\n\n </table>'}
  ]

  for (const tempData of template) {
    const exists = await payload.find({
      collection: CACHE_TAG_EMAIL_TEMP,
      where: { template_name: { equals: tempData.template_name } },
      limit: 1,
    })

    if (!exists.docs.length) {
      await payload.create({
        collection: CACHE_TAG_EMAIL_TEMP,
        data: tempData,
      })
      payload.logger.info(`Created tempData: ${tempData.template_name}`)
    }
  }

  payload.logger.info('tempDatas seeded successfully')
}
